feat: scope instance decorators
immobiliare/fastify-metrics pull request #116
Opened 2022-02-21 13:13 UTC by dnlup

Use a `metrics` object to scope instance decorators.

BREAKING CHANGE: the fastify instance decorators are exported in the `metrics` object.
The `doc` sampler instance is renamed to `sampler`.

2022-02-22 10:33 UTC, antoniomuso commented on index.js
> +        // fastify.decorate(
Why do not you remove these comments?

2022-02-22 10:41 UTC, antoniomuso approved these changes

2022-02-22 10:45 UTC, simonecorsi requested changes

2022-02-22 10:50 UTC, dnlup commented on index.js
> +        // fastify.decorate(
Sorry, I forgot. Thanks

2022-02-22 10:50 UTC, dnlup commented on index.js
> +        // fastify.decorate('hrtime2s', hrtime2s);
Sure, sorry I missed them

2022-02-22 11:27 UTC, merged

2022-03-10 10:12 UTC, simonecorsi commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@immobiliarelabs/fastify-metrics/v/2.0.0)
- [GitHub release](https://github.com/immobiliare/fastify-metrics/releases/tag/v2.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: